name: Explore Runner

on:
  push:

jobs:
  explore-runner:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Show Node version
        run: node -v

      - name: Show npm version
        run: npm -v

      - name: Show current directory
        run: pwd

      - name: List project files
        run: ls -la
